# Generated by Django 4.2.16 on 2024-12-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='BooleanField',
        ),
        migrations.RemoveField(
            model_name='game',
            name='DecimaField',
        ),
    ]
